-- MySQL Script generated by MySQL Workbench
-- Thu Oct 17 17:20:16 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema freelans
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema freelans
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `freelans` DEFAULT CHARACTER SET utf8 ;
USE `freelans` ;

-- -----------------------------------------------------
-- Table `freelans`.`freelanser_akks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `freelans`.`freelanser_akks` (
  `id_f` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `telegram` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `spacialty` VARCHAR(150) NOT NULL,
  `rating` FLOAT NOT NULL,
  `bank_card` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_f`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `freelans`.`cliants_akks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `freelans`.`cliants_akks` (
  `id_c` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `telegram` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `rating` FLOAT NOT NULL,
  PRIMARY KEY (`id_c`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `freelans`.`job`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `freelans`.`job` (
  `id_j` INT NOT NULL AUTO_INCREMENT,
  `lable` VARCHAR(45) NOT NULL,
  `spacsalyty` VARCHAR(150) NOT NULL,
  `tipe` VARCHAR(45) NOT NULL,
  `description` VARCHAR(500) NOT NULL,
  `id_f` INT NOT NULL,
  `id_c` INT NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `price` DECIMAL(20,2) NOT NULL,
  PRIMARY KEY (`id_j`),
  INDEX `freelanser_akks_idx` (`id_f` ASC) VISIBLE,
  INDEX `cliants_akks_idx` (`id_c` ASC) VISIBLE,
  CONSTRAINT `freelanser_akks`
    FOREIGN KEY (`id_f`)
    REFERENCES `freelans`.`freelanser_akks` (`id_f`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `cliants_akks`
    FOREIGN KEY (`id_c`)
    REFERENCES `freelans`.`cliants_akks` (`id_c`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
